apiVersion: v1
data:
  MYSQL_ROOT_PASSWORD: cm9vdHBhc3N3b3Jk
kind: Secret
metadata:
  creationTimestamp: "2023-07-05T09:11:37Z"
  name: db-secret
  namespace: default
  resourceVersion: "1254524"
  uid: 6bad7d74-afa2-43db-976f-7e0a73977bb8
type: Opaque
