apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2023-07-05T09:14:00Z"
  labels:
    run: mysql-pod
  name: db-service
  namespace: default
  resourceVersion: "1255008"
  uid: e3d714b9-aea8-4194-a411-3d85246eff0c
spec:
  clusterIP: 10.111.206.121
  clusterIPs:
  - 10.111.206.121
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    run: mysql-pod
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
